site_name: Dredd
repo_url: 'https://github.com/apiaryio/dredd'
site_description: 'HTTP API Testing Framework'
site_author: 'Apiary'

pages:
  - Dredd:
    - About Dredd: index.md
    - Quickstart: quickstart.md
    - How It Works: how-it-works.md
  - Usage:
    - Command-line Interface: usage-cli.md
    - From JavaScript: usage-js.md
  - Hooks:
    - About Hooks: hooks.md
    - Supported Languages:
      - Go: hooks-go.md
      - JavaScript (Sandboxed): hooks-js-sandbox.md
      - Node.js: hooks-nodejs.md
      - Perl: hooks-perl.md
      - PHP: hooks-php.md
      - Python: hooks-python.md
      - Ruby: hooks-ruby.md
    - Other Languages: hooks-new-language.md
  - Guides:
    - How-To Guides: how-to-guides.md
    - Full Example: example.md

theme: readthedocs
markdown_extensions:
  - toc:
      permalink: true

# These extra_templates exists only to redirect from old URLs to new URLs.
# This is more properly done using an HTTP redirect, but unfortunately
# readthedocs.org's page redirection is broken (see
# https://github.com/rtfd/readthedocs.org/issues/1826). Once that bug is fixed,
# these files can be removed.
extra_templates:
  - usage.html
  - usage/index.html
  - overview.html
  - overview/index.html
  - execution-lifecycle.html
  - execution-lifecycle/index.html
