version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
